CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Disciplines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NameDiscipline" text NOT NULL,
    "Course" integer NOT NULL,
    "isMagistracy" boolean NOT NULL,
    CONSTRAINT "PK_Disciplines" PRIMARY KEY ("Id")
);

CREATE TABLE "Groups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(30) NOT NULL,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(256) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "MiddleName" character varying(100),
    "Role" smallint NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "TrainedGroups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "isAS" boolean NOT NULL,
    "isPO" boolean NOT NULL,
    "isVM" boolean NOT NULL,
    "DisciplineId" integer NOT NULL,
    CONSTRAINT "PK_TrainedGroups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TrainedGroups_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Admins" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Position" character varying(100) NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Admins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Educators" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Profession" text NOT NULL,
    "FullName" text,
    "AcademicDegree" text,
    CONSTRAINT "PK_Educators" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Educators_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Students" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "StudentCard" character varying(20) NOT NULL,
    CONSTRAINT "PK_Students" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Students_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Students_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EducatorAdditionalInfos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EducatorId" integer NOT NULL,
    "EducationLevel" text NOT NULL,
    "AcademicTitle" text NOT NULL,
    "SpecialtyOrFieldOfStudy" text NOT NULL,
    "Qualification" text NOT NULL,
    "AdditionalInfo" text NOT NULL,
    "Image" bytea NOT NULL,
    CONSTRAINT "PK_EducatorAdditionalInfos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EducatorAdditionalInfos_Educators_EducatorId" FOREIGN KEY ("EducatorId") REFERENCES "Educators" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskEducation" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DiciplineId" integer NOT NULL,
    "EducatorId" integer NOT NULL,
    "TaskName" text NOT NULL,
    "TaskDescription" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskEducation" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskEducation_Disciplines_DiciplineId" FOREIGN KEY ("DiciplineId") REFERENCES "Disciplines" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TaskEducation_Educators_EducatorId" FOREIGN KEY ("EducatorId") REFERENCES "Educators" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "EducatorDisciplines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EducatorAdditionalInfoId" integer NOT NULL,
    "DisciplineId" integer NOT NULL,
    CONSTRAINT "PK_EducatorDisciplines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EducatorDisciplines_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EducatorDisciplines_EducatorAdditionalInfos_EducatorAdditio~" FOREIGN KEY ("EducatorAdditionalInfoId") REFERENCES "EducatorAdditionalInfos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StudentSolutions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "SolutionText" text NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StudentSolutions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentSolutions_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StudentSolutions_TaskEducation_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskEducation" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TaskFile" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "FileName" text NOT NULL,
    "PhysicalPath" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "FileType" text NOT NULL,
    CONSTRAINT "PK_TaskFile" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskFile_TaskEducation_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskEducation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskGroups" (
    "GroupsId" integer NOT NULL,
    "TaskEducationsId" integer NOT NULL,
    CONSTRAINT "PK_TaskGroups" PRIMARY KEY ("GroupsId", "TaskEducationsId"),
    CONSTRAINT "FK_TaskGroups_Groups_GroupsId" FOREIGN KEY ("GroupsId") REFERENCES "Groups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskGroups_TaskEducation_TaskEducationsId" FOREIGN KEY ("TaskEducationsId") REFERENCES "TaskEducation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SolutionChats" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SolutionId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SolutionChats" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SolutionChats_StudentSolutions_SolutionId" FOREIGN KEY ("SolutionId") REFERENCES "StudentSolutions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SolutionFiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SolutionId" integer NOT NULL,
    "FileName" text NOT NULL,
    "OriginalFileName" text NOT NULL,
    "PhysicalPath" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "FileType" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SolutionFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SolutionFiles_StudentSolutions_SolutionId" FOREIGN KEY ("SolutionId") REFERENCES "StudentSolutions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ChatParticipants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SolutionChatId" integer NOT NULL,
    "SenderId" integer NOT NULL,
    "HasUnreadMessages" boolean NOT NULL,
    CONSTRAINT "PK_ChatParticipants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatParticipants_SolutionChats_SolutionChatId" FOREIGN KEY ("SolutionChatId") REFERENCES "SolutionChats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MessagesInChat" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChatId" integer NOT NULL,
    "SenderId" integer NOT NULL,
    "SenderRole" smallint NOT NULL,
    "MessageText" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MessagesInChat" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessagesInChat_SolutionChats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "SolutionChats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FilesInChat" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "FileName" text NOT NULL,
    "PhysicalPath" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "FileType" text NOT NULL,
    CONSTRAINT "PK_FilesInChat" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FilesInChat_MessagesInChat_MessageId" FOREIGN KEY ("MessageId") REFERENCES "MessagesInChat" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Admins_UserId" ON "Admins" ("UserId");

CREATE INDEX "IX_ChatParticipants_SenderId" ON "ChatParticipants" ("SenderId");

CREATE INDEX "IX_ChatParticipants_SolutionChatId" ON "ChatParticipants" ("SolutionChatId");

CREATE UNIQUE INDEX "IX_ChatParticipants_SolutionChatId_SenderId" ON "ChatParticipants" ("SolutionChatId", "SenderId");

CREATE INDEX "IX_Disciplines_Course" ON "Disciplines" ("Course");

CREATE UNIQUE INDEX "IX_EducatorAdditionalInfos_EducatorId" ON "EducatorAdditionalInfos" ("EducatorId");

CREATE INDEX "IX_EducatorDisciplines_DisciplineId" ON "EducatorDisciplines" ("DisciplineId");

CREATE INDEX "IX_EducatorDisciplines_EducatorAdditionalInfoId" ON "EducatorDisciplines" ("EducatorAdditionalInfoId");

CREATE UNIQUE INDEX "IX_Educators_UserId" ON "Educators" ("UserId");

CREATE INDEX "IX_FilesInChat_MessageId" ON "FilesInChat" ("MessageId");

CREATE INDEX "IX_MessagesInChat_ChatId" ON "MessagesInChat" ("ChatId");

CREATE UNIQUE INDEX "IX_SolutionChats_SolutionId" ON "SolutionChats" ("SolutionId");

CREATE INDEX "IX_SolutionFiles_SolutionId" ON "SolutionFiles" ("SolutionId");

CREATE INDEX "IX_Students_GroupId" ON "Students" ("GroupId");

CREATE UNIQUE INDEX "IX_Students_StudentCard" ON "Students" ("StudentCard");

CREATE UNIQUE INDEX "IX_Students_UserId" ON "Students" ("UserId");

CREATE INDEX "IX_StudentSolutions_StudentId" ON "StudentSolutions" ("StudentId");

CREATE INDEX "IX_StudentSolutions_TaskId" ON "StudentSolutions" ("TaskId");

CREATE INDEX "IX_TaskEducation_DiciplineId" ON "TaskEducation" ("DiciplineId");

CREATE INDEX "IX_TaskEducation_EducatorId" ON "TaskEducation" ("EducatorId");

CREATE INDEX "IX_TaskFile_TaskId" ON "TaskFile" ("TaskId");

CREATE INDEX "IX_TaskGroups_TaskEducationsId" ON "TaskGroups" ("TaskEducationsId");

CREATE UNIQUE INDEX "IX_TrainedGroups_DisciplineId" ON "TrainedGroups" ("DisciplineId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260603223052_InitialCreate', '9.0.11');

COMMIT;

