// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.DAL.Context.ApplicationDbContext;

#nullable disable

namespace Server.DAL.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20260403160038_AddSolution")]
    partial class AddSolution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupTaskEducation", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskEducationsId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsId", "TaskEducationsId");

                    b.HasIndex("TaskEducationsId");

                    b.ToTable("TaskGroups", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.FileInChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("FilesInChat", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.MessageInChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<byte>("SenderRole")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("MessagesInChat", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.SolutionChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SolutionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId")
                        .IsUnique();

                    b.ToTable("SolutionChats", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.SolutionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolutionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("SolutionFiles", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.StudentSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SolutionChatId")
                        .HasColumnType("integer");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TaskId");

                    b.ToTable("StudentSolutions", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("NameDiscipline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isMagistracy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Course");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.Educator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Educators");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.EducatorAdditionalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EducatorId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialtyOrFieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducatorId")
                        .IsUnique();

                    b.ToTable("EducatorAdditionalInfos");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.EducatorDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("EducatorAdditionalInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("EducatorAdditionalInfoId");

                    b.ToTable("EducatorDisciplines");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.TrainedGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<bool>("isAS")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPO")
                        .HasColumnType("boolean");

                    b.Property<bool>("isVM")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId")
                        .IsUnique();

                    b.ToTable("TrainedGroups");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.TaskEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("EducatorId")
                        .HasColumnType("integer");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiciplineId");

                    b.HasIndex("EducatorId");

                    b.ToTable("TaskEducation", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.TaskFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskFile", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentCard")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentCard")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GroupTaskEducation", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DAL.Models.Entities.TaskEducation", null)
                        .WithMany()
                        .HasForeignKey("TaskEducationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.FileInChat", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Education.MessageInChat", "Message")
                        .WithMany("Files")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.MessageInChat", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Education.SolutionChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.SolutionChat", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Education.StudentSolution", "Solution")
                        .WithOne("SolutionChat")
                        .HasForeignKey("Server.DAL.Models.Entities.Education.SolutionChat", "SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.SolutionFile", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Education.StudentSolution", "Solution")
                        .WithMany("SolutionFiles")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.StudentSolution", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Users.Student", "Student")
                        .WithMany("Solutions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.DAL.Models.Entities.TaskEducation", "Task")
                        .WithMany("StudentSolutions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.Educator", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Users.User", "User")
                        .WithOne("Educator")
                        .HasForeignKey("Server.DAL.Models.Entities.Educators.Educator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.EducatorAdditionalInfo", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Educators.Educator", null)
                        .WithOne("EducatorAdditionalInfo")
                        .HasForeignKey("Server.DAL.Models.Entities.Educators.EducatorAdditionalInfo", "EducatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.EducatorDiscipline", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Educators.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DAL.Models.Entities.Educators.EducatorAdditionalInfo", null)
                        .WithMany("EducatorDisciplines")
                        .HasForeignKey("EducatorAdditionalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.TrainedGroup", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Educators.Discipline", "Discipline")
                        .WithOne("Group")
                        .HasForeignKey("Server.DAL.Models.Entities.Educators.TrainedGroup", "DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.TaskEducation", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Educators.Discipline", "Dicipline")
                        .WithMany("TaskEducations")
                        .HasForeignKey("DiciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.DAL.Models.Entities.Educators.Educator", "Educator")
                        .WithMany("TaskEducations")
                        .HasForeignKey("EducatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dicipline");

                    b.Navigation("Educator");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.TaskFile", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.TaskEducation", "Task")
                        .WithMany("Files")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.Admin", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Users.User", "User")
                        .WithOne("Administrator")
                        .HasForeignKey("Server.DAL.Models.Entities.Users.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.Student", b =>
                {
                    b.HasOne("Server.DAL.Models.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.DAL.Models.Entities.Users.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Server.DAL.Models.Entities.Users.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.MessageInChat", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.SolutionChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Education.StudentSolution", b =>
                {
                    b.Navigation("SolutionChat");

                    b.Navigation("SolutionFiles");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.Discipline", b =>
                {
                    b.Navigation("Group");

                    b.Navigation("TaskEducations");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.Educator", b =>
                {
                    b.Navigation("EducatorAdditionalInfo")
                        .IsRequired();

                    b.Navigation("TaskEducations");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Educators.EducatorAdditionalInfo", b =>
                {
                    b.Navigation("EducatorDisciplines");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.TaskEducation", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("StudentSolutions");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.Student", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Server.DAL.Models.Entities.Users.User", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Educator");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
